### ISSUE TITLE
"Connection Failed" when sending a new message

### ISSUE THREAD

**Issue by TheKildar** [fetlife/android#230]
Steps to reproduce:
1. Click "new message" action.
2. Select friend for message.
3. Type message.
4. Send.

Response: "Connection failed, try again later"

However, other actions requiring connectivity work.

I have not been able to start a conversation from the app.  I can reply to existing conversations.

**Comment by TheKildar** [comment]
This may be related to #205?

**Comment by kistitan** [comment]
Hi @TheKildar,

Thank you for reporting this issue.
Do I understand correctly that this does happen all the time? Or did it happen only once?

Thank you

**Comment by TheKildar** [comment]
Every time.

**Comment by kistitan** [comment]
Thank you.
Issues has been found and fixed. 
Fix will be there in the next version

**Comment by kistitan** [comment]
fixed in version 2.1

**Comment by miyuu-tomasu** [comment]
"connection failed please try again later" 
same steps to reproduce as above ( TheKildar commented on 5 Dec 2016 )
i am getting this for new sent messages and also for replies in v2.3.2

**Comment by kistitan** [comment]
Hi @miyuu-tomasu,

Thank you for reporting this issue.
We are going to look at it ASAP.

**Comment by kistitan** [comment]
Hi @miyuu-tomasu,

We tried, but was not able to reproduce this with our test devices.
As a first round, may I ask if you can still reproduce the issue and if yes does it happen with one particular friend, or with any of your friends?

Thank you.

**Comment by miyuu-tomasu** [comment]
i get the connection failed msg on the conversations screen,  when i try to send a new msg,  and when i reply to an existing msg thread. i've msged 3 different ppl and it has happened with all of them.  Just downloaded v2.4.0  and it is still happening.  

just wondering.... Would doing a complete uninstall of the current apk,  then a clean reinstall possibly help?  (perhaps it's residual during the overwriting) 
if yes,  do you have a walk through posted on how to do a complete uninstall ?

**Comment by kistitan** [comment]
Hi again,

That's very strange as basically we don't notice any similar behaviour with the same codebase.
Uninstall usually should be pretty easy.
Just long press on the App icon and either drag it to the appearing trash or select uninstall from the drop down menu. It depends on the device.
Let us know how does it go after the reinstall.

Thank you

**Comment by miyuu-tomasu** [comment]
long press only does a soft uninstall with quite a few legacy and residual files remaining, and a reinstall over that has the same connection problem. 
So i ended up doing a completely new install and the connection problem is fixed.

**Comment by kistitan** [comment]
That's good news. Thanks for letting us know.
