### ISSUE TITLE
Not able to log into the app

### ISSUE THREAD

**Issue by Willow-Rose** [fetlife/android#457]
So for a few months now I've been getting this message "Server could not be reached. Please check your internet connection." I've checked my connection and everything is fine. Everything in the app looked fine as well. Today I received notifications like normal, but when I get into the app it is just a black screen now. I can see the menu, but not my feed nor my conversations. I uninstalled then re-installed and now I can't even log in. Internet is still 100% fine.

**Comment by FernandoMiguel** [comment]
Maybe you are one of the users with a weak password that was forced to change?
Try resetting your password

**Comment by kistitan** [comment]
@Willow-Rose 
We had a security update yesterday, that accidentally made the App not being able to be used by several users. The issue should be solved withing 24 hours by itself, but if you need fast solution you can install the hotfix version of : https://github.com/fetlife/android/releases/download/v2.15.5/fetlife-2.15.5.apk

Please let us know if connectivity issues are not solved withing this time frame or by installing this version.

Thank you

**Comment by Willow-Rose** [comment]
@kistitan I now have usernames and wording, but no pictures are loading.

**Comment by johnbaku** [comment]
@Willow-Rose are you still having the problem or is it resolved now?

**Comment by Willow-Rose** [comment]
I'm still having the problem, but I made a new issue about it.
